# C1-9:CHAT-DISP-01 / CHAT-TOOL-01/02 / CHAT-API-01 — E2E scenarios

"""End-to-end tests for the chat-first + HITL pipeline using FastAPI TestClient
with fully mocked LLM and graph helpers.

Covers the 6 E2E scenarios from docs/L1-components/C1-9_Chat_Layer.md §E2E
Test Coverage and the test plan generated by /plan-eng-review:

  E2E-1 — Golden path: chitchat → build → HITL confirm → deploy → workflow_url
  E2E-2 — Plan edit path: build → HITL → edit step → resume → deploy
  E2E-3 — Plan reject path: build → HITL → reject → session preserved, can chat
  E2E-4 — Keyword fast-path: keyword in first turn → build called, no extra clarification
  E2E-5 — Clarification convergence: 3 ambiguous turns → LLM never calls tool
  E2E-6 — Error recovery: build fails (graph error) → friendly message, session preserved

All LLM calls are replaced by AIMessage stubs; graph helpers
(run_graph_until_interrupt, resume_graph_with_confirmation) are mocked so no
LangGraph or OpenAI endpoint is needed.

Strategy
--------
We exercise the dispatcher directly (not via the HTTP layer) to avoid the
FastAPI / asyncio overhead. The HTTP-layer mapping tests are in
test_routes_chat.py. E2E tests here validate the full multi-turn state
machine: session persistence, history accumulation, HITL flag transitions.
"""

from __future__ import annotations

from typing import Any
from unittest.mock import MagicMock, patch

import pytest
from langchain_core.messages import AIMessage

from app.chat import session_store as ss_module
from app.chat.dispatcher import dispatch_chat_turn
from app.chat.session_store import get_session_store
from app.models.agent_state import AgentState
from app.models.enums import StepIntent
from app.models.planning import StepPlan


# ---------------------------------------------------------------------------
# Fixtures & Helpers
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _reset_store():
    """Isolate each test with a clean SessionStore singleton."""
    ss_module._store_instance = None
    yield
    ss_module._store_instance = None


def _step(step_id: str, intent=StepIntent.ACTION) -> StepPlan:
    return StepPlan(
        step_id=step_id,
        description=f"description for {step_id}",
        intent=intent,
        candidate_node_types=["n8n-nodes-base.httpRequest"],
        reason="test",
    )


def _agent_state(**kwargs: Any) -> AgentState:
    defaults: dict[str, Any] = {"user_message": "test"}
    defaults.update(kwargs)
    return AgentState(**defaults)


def _text(content: str) -> AIMessage:
    return AIMessage(content=content)


def _tool_call(name: str, args: dict, tool_id: str = "call_1") -> AIMessage:
    return AIMessage(
        content="",
        tool_calls=[{"id": tool_id, "name": name, "args": args}],
    )


class _MockLLM:
    """Configurable LLM stub for a sequence of pre-programmed responses."""

    def __init__(self, responses: list[AIMessage]):
        self._responses = list(responses)
        self._call_count = 0
        self._bound_responses: list[AIMessage] | None = None

    def bind_tools(self, tools, **kwargs) -> "_MockLLM":
        """Return a bound variant that delegates back to this object."""
        bound = _MockLLM(self._responses[:])
        bound._responses = self._responses  # shared reference
        bound._call_count = 0
        # Save reference to tool_choice to decide behaviour
        bound._tool_choice = kwargs.get("tool_choice")
        return bound

    def invoke(self, messages) -> AIMessage:
        if self._responses:
            resp = self._responses.pop(0)
            self._call_count += 1
            return resp
        # Fallback: return empty text
        return _text("(mock exhausted)")


def _build_patches(llm: _MockLLM, tool_results: list[dict[str, Any]]):
    """Return context managers that wire the mock LLM and tool results."""
    tool_result_iter = iter(tool_results)

    def _make_tools(session_id, **kwargs):
        build_tool = MagicMock()
        build_tool.name = "build_workflow"
        confirm_tool = MagicMock()
        confirm_tool.name = "confirm_plan"

        def _invoke_build(args):
            return next(tool_result_iter, {
                "ok": False, "status": "error", "error_message": "exhausted"
            })

        def _invoke_confirm(args):
            return next(tool_result_iter, {
                "ok": False, "status": "error", "error_message": "exhausted"
            })

        build_tool.invoke.side_effect = _invoke_build
        confirm_tool.invoke.side_effect = _invoke_confirm
        return [build_tool, confirm_tool]

    p_llm = patch("app.chat.dispatcher._make_chat_llm", return_value=llm)
    p_tools = patch("app.chat.dispatcher.make_chat_tools", side_effect=_make_tools)
    return p_llm, p_tools


# ---------------------------------------------------------------------------
# E2E-1 — Golden path: chitchat → clarification → build → confirm → deploy
# ---------------------------------------------------------------------------


def test_e2e_1_golden_path_chitchat_build_confirm_deploy():
    """E2E-1: Multi-turn chitchat, then build_workflow + HITL confirm → deployed."""
    plan = [
        _step("step_1", StepIntent.TRIGGER),
        _step("step_2", StepIntent.ACTION),
    ]
    plan_state = _agent_state(plan=plan)
    deploy_state = _agent_state(
        plan=plan,
        workflow_url="https://n8n/w/42",
        workflow_id="wf42",
    )

    # Sequence: chitchat → clarification question → build → confirm → friendly deploy
    llm_responses = [
        _text("Hi! How can I help you today?"),          # turn 1: chitchat
        _text("What would you like to automate?"),        # turn 2: clarification
        _tool_call("build_workflow", {"user_request": "fetch github stars hourly to sheet"}),  # turn 3: decision
        _text("Great! Here is the plan: 1. Trigger every hour 2. Fetch data. Confirm?"),       # turn 3: humanise
        _tool_call("confirm_plan", {"approved": True}),  # turn 4: user confirms
        _text("Deployed! Your workflow is live at https://n8n/w/42"),  # turn 4: humanise
    ]

    tool_results = [
        {
            "ok": True,
            "status": "awaiting_plan_approval",
            "plan_summary": "1. trigger hourly\n2. fetch github",
            "plan": [s.model_dump(mode="json") for s in plan],
            "session_id": "e2e_sess_001",
        },
        {
            "ok": True,
            "status": "deployed",
            "workflow_url": "https://n8n/w/42",
            "workflow_id": "wf42",
        },
    ]

    llm = _MockLLM(llm_responses)
    p_llm, p_tools = _build_patches(llm, tool_results)

    with p_llm, p_tools:
        # Turn 1: pure chitchat
        r1 = dispatch_chat_turn(None, "Hello there!")
        assert r1.status == "chat"
        assert r1.workflow_url is None
        sid = r1.session_id

        # Turn 2: clarification question from the model
        r2 = dispatch_chat_turn(sid, "I want to automate something")
        assert r2.status == "chat"

        # Turn 3: clear request → LLM calls build_workflow
        r3 = dispatch_chat_turn(sid, "Every hour fetch github stars and save to Google Sheet")
        assert r3.status == "awaiting_plan_approval"
        assert r3.workflow_url is None
        # Session should be marked as awaiting
        sess = get_session_store().get(sid)
        assert sess is not None
        assert sess.awaiting_plan_approval is True

        # Turn 4: user confirms → LLM calls confirm_plan(approved=True) → deployed
        r4 = dispatch_chat_turn(sid, "確認")
        assert r4.status == "deployed"
        assert r4.workflow_url == "https://n8n/w/42"
        assert r4.workflow_id == "wf42"

    # Session history should span all 4 turns
    sess = get_session_store().get(sid)
    assert sess is not None
    assert len(sess.history) >= 4  # at least user messages


# ---------------------------------------------------------------------------
# E2E-2 — Plan edit path: build → HITL → edit → resume → deploy
# ---------------------------------------------------------------------------


def test_e2e_2_plan_edit_path():
    """E2E-2: User edits a step in the plan before confirming."""
    plan = [
        _step("step_1", StepIntent.TRIGGER),
        _step("step_2", StepIntent.ACTION),
    ]

    llm_responses = [
        _tool_call("build_workflow", {"user_request": "hourly fetch and send slack"}),
        _text("Here's the plan. Step 2 currently uses HTTP. Want to change it?"),
        # User says "change step 2 to Slack" → LLM calls confirm with edits
        _tool_call("confirm_plan", {
            "approved": True,
            "edits": [{"step_id": "step_2", "candidate_node_types": ["n8n-nodes-base.slack"]}],
        }),
        _text("Plan updated and deployed with Slack node!"),
    ]

    tool_results = [
        {
            "ok": True,
            "status": "awaiting_plan_approval",
            "plan_summary": "1. trigger\n2. http fetch",
            "plan": [s.model_dump(mode="json") for s in plan],
        },
        {
            "ok": True,
            "status": "deployed",
            "workflow_url": "https://n8n/w/99",
            "workflow_id": "wf99",
        },
    ]

    llm = _MockLLM(llm_responses)
    p_llm, p_tools = _build_patches(llm, tool_results)

    with p_llm, p_tools:
        # Turn 1: clear request → build
        r1 = dispatch_chat_turn(None, "Every hour fetch data and send Slack message")
        assert r1.status == "awaiting_plan_approval"
        sid = r1.session_id

        # Turn 2: user requests edit → confirm with edits → deployed
        r2 = dispatch_chat_turn(sid, "Change step 2 to Slack node please")
        assert r2.status == "deployed"
        assert r2.workflow_url == "https://n8n/w/99"


# ---------------------------------------------------------------------------
# E2E-3 — Plan reject path: build → HITL → reject → session preserved
# ---------------------------------------------------------------------------


def test_e2e_3_plan_reject_session_preserved():
    """E2E-3: User rejects the plan; session keeps history and can continue chatting."""
    plan = [_step("step_1", StepIntent.TRIGGER), _step("step_2", StepIntent.ACTION)]

    llm_responses = [
        _tool_call("build_workflow", {"user_request": "build automation"}),
        _text("Here's the plan. Do you want to proceed?"),
        # User rejects
        _tool_call("confirm_plan", {"approved": False, "feedback": "wrong approach"}),
        _text("No problem, I've cancelled the plan. What would you like to do instead?"),
        # Continued chat after rejection
        _text("Sure, let me know your revised requirements."),
    ]

    tool_results = [
        {
            "ok": True,
            "status": "awaiting_plan_approval",
            "plan_summary": "1. trigger\n2. action",
            "plan": [s.model_dump(mode="json") for s in plan],
        },
        {
            "ok": True,
            "status": "rejected",
            "message": "plan rejected; you can refine the request and try again.",
        },
    ]

    llm = _MockLLM(llm_responses)
    p_llm, p_tools = _build_patches(llm, tool_results)

    with p_llm, p_tools:
        # Turn 1: build
        r1 = dispatch_chat_turn(None, "Build me an automation workflow")
        assert r1.status == "awaiting_plan_approval"
        sid = r1.session_id

        # Turn 2: reject
        r2 = dispatch_chat_turn(sid, "不要了, wrong approach")
        assert r2.status == "rejected"
        # Session must still exist
        sess = get_session_store().get(sid)
        assert sess is not None
        # After rejection, awaiting_plan_approval should be cleared
        assert sess.awaiting_plan_approval is False

        # Turn 3: continued chat after rejection — session is usable
        r3 = dispatch_chat_turn(sid, "I'll think about what I need")
        assert r3.status == "chat"
        assert r3.session_id == sid


# ---------------------------------------------------------------------------
# E2E-4 — Keyword fast-path: 1 turn → build → HITL → deploy (no extra clarification)
# ---------------------------------------------------------------------------


def test_e2e_4_keyword_fast_path_one_turn_build():
    """E2E-4: A clear keyword-rich request → build_workflow called in turn 1."""
    plan = [_step("step_1", StepIntent.TRIGGER), _step("step_2", StepIntent.ACTION)]

    llm_responses = [
        # First response immediately calls build — no clarification requested
        _tool_call("build_workflow", {
            "user_request": "每小時自動化抓取 github stars 並存到 Google Sheet",
            "clarifications": {"frequency": "hourly"},
        }),
        _text("已生成計畫：1. 每小時觸發 2. 抓取 GitHub stars 3. 存入 Sheet。請確認？"),
    ]

    tool_results = [
        {
            "ok": True,
            "status": "awaiting_plan_approval",
            "plan_summary": "1. schedule trigger\n2. http request\n3. google sheets",
            "plan": [s.model_dump(mode="json") for s in plan],
        },
    ]

    llm = _MockLLM(llm_responses)
    p_llm, p_tools = _build_patches(llm, tool_results)

    with p_llm, p_tools:
        # Single turn with clear keyword-rich message
        r1 = dispatch_chat_turn(
            None,
            "幫我建立 workflow 每小時自動化抓取 github stars 並存到 Google Sheet",
        )

    # Keyword-matched request should immediately trigger build
    assert r1.status == "awaiting_plan_approval"
    assert len(r1.tool_calls) == 1
    assert r1.tool_calls[0]["name"] == "build_workflow"
    # No workflow_url yet — still waiting for confirmation
    assert r1.workflow_url is None


# ---------------------------------------------------------------------------
# E2E-5 — Clarification convergence: 3 ambiguous turns → LLM never calls tool
# ---------------------------------------------------------------------------


def test_e2e_5_ambiguous_3_turns_no_tool_call():
    """E2E-5: 3 turns of ambiguous requests → LLM asks clarifying questions, never calls tool."""
    # All 3 user-facing LLM responses + potential humanise calls — none use tool_calls
    llm_responses = [
        _text("I'd be happy to help! Could you tell me what you want to automate?"),
        _text("Could you clarify the trigger — should this run on a schedule or a webhook?"),
        _text("And what should happen with the data — where should it be sent or stored?"),
    ]

    llm = _MockLLM(llm_responses)
    p_llm, p_tools = _build_patches(llm, [])  # no tool results needed

    with p_llm, p_tools:
        r1 = dispatch_chat_turn(None, "我想做點自動化")
        assert r1.status == "chat"
        assert r1.tool_calls == []
        sid = r1.session_id

        r2 = dispatch_chat_turn(sid, "就是一些流程之類的")
        assert r2.status == "chat"
        assert r2.tool_calls == []

        r3 = dispatch_chat_turn(sid, "自動化之類的")
        assert r3.status == "chat"
        assert r3.tool_calls == []

    # All 3 turns should be in history
    sess = get_session_store().get(sid)
    assert sess is not None
    # Each turn adds user + assistant = 2 messages, so 3 turns = 6 messages
    assert len(sess.history) >= 4


# ---------------------------------------------------------------------------
# E2E-6 — Error recovery: build fails → LLM explains, session preserved
# ---------------------------------------------------------------------------


def test_e2e_6_build_fails_session_preserved():
    """E2E-6: build_workflow returns error → LLM produces friendly error message, session preserved."""
    llm_responses = [
        _tool_call("build_workflow", {"user_request": "complex impossible workflow"}),
        _text("I tried to build the workflow but it timed out. Could you simplify the request?"),
    ]

    tool_results = [
        {
            "ok": False,
            "status": "error",
            "error_category": "building_timeout",
            "error_message": "building_timeout: LLM exceeded 180s",
        },
    ]

    llm = _MockLLM(llm_responses)
    p_llm, p_tools = _build_patches(llm, tool_results)

    with p_llm, p_tools:
        r1 = dispatch_chat_turn(None, "自動化一個複雜的工作流程")

    # Status reflects the tool's error
    assert r1.status == "error"
    assert "timeout" in r1.assistant_text.lower() or "tried" in r1.assistant_text.lower()
    # error_message should be present
    assert r1.error_message is not None

    # Session must still exist — user can continue chatting
    sess = get_session_store().get(r1.session_id)
    assert sess is not None

    # Follow-up chat in same session should work fine
    llm_responses_2 = [_text("Sure, let's try a simpler approach.")]
    llm2 = _MockLLM(llm_responses_2)
    p_llm2, p_tools2 = _build_patches(llm2, [])

    with p_llm2, p_tools2:
        r2 = dispatch_chat_turn(r1.session_id, "Let me simplify")
    assert r2.status == "chat"
    assert r2.session_id == r1.session_id


# ---------------------------------------------------------------------------
# Multi-turn history accumulation check
# ---------------------------------------------------------------------------


def test_e2e_history_accumulates_across_turns():
    """Sessions accumulate history across multiple chat turns."""
    llm_responses = [
        _text("turn 1 response"),
        _text("turn 2 response"),
        _text("turn 3 response"),
    ]

    llm = _MockLLM(llm_responses)
    p_llm, p_tools = _build_patches(llm, [])

    with p_llm, p_tools:
        r1 = dispatch_chat_turn(None, "message one")
        sid = r1.session_id
        dispatch_chat_turn(sid, "message two")
        dispatch_chat_turn(sid, "message three")

    sess = get_session_store().get(sid)
    assert sess is not None
    # 3 user messages + 3 assistant replies = 6 history entries minimum
    user_msgs = [m for m in sess.history if m.get("role") == "user"]
    asst_msgs = [m for m in sess.history if m.get("role") == "assistant"]
    assert len(user_msgs) == 3
    assert len(asst_msgs) == 3


# ---------------------------------------------------------------------------
# HITL state transition sanity
# ---------------------------------------------------------------------------


def test_e2e_hitl_flags_cleared_after_deploy():
    """After a successful deployment, awaiting_plan_approval is False and no pending summary."""
    plan = [_step("s1")]

    llm_responses = [
        _tool_call("build_workflow", {"user_request": "build X"}),
        _text("Plan ready. Confirm?"),
        _tool_call("confirm_plan", {"approved": True}),
        _text("Deployed at https://n8n/w/7"),
    ]

    tool_results = [
        {
            "ok": True,
            "status": "awaiting_plan_approval",
            "plan_summary": "step 1 summary",
            "plan": [s.model_dump(mode="json") for s in plan],
        },
        {
            "ok": True,
            "status": "deployed",
            "workflow_url": "https://n8n/w/7",
            "workflow_id": "wf7",
        },
    ]

    llm = _MockLLM(llm_responses)
    p_llm, p_tools = _build_patches(llm, tool_results)

    with p_llm, p_tools:
        r1 = dispatch_chat_turn(None, "build me a workflow please")
        sid = r1.session_id
        sess_mid = get_session_store().get(sid)
        assert sess_mid is not None
        assert sess_mid.awaiting_plan_approval is True
        assert sess_mid.pending_plan_summary is not None

        r2 = dispatch_chat_turn(sid, "確認，部署吧")
        assert r2.status == "deployed"
        sess_final = get_session_store().get(sid)
        assert sess_final is not None
        assert sess_final.awaiting_plan_approval is False
        assert sess_final.pending_plan_summary is None
